<?php

namespace Database\Seeders;

use App\Models\Quote;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class QuotesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $quotes = [
            "11 players, 1 heartbeat",
            "The beautiful game",
            "A pass, a shot, a goal",
            "Score with your feet, win with your heart",
            "Winning is a habit",
            "Success starts with belief",
            "Believe, achieve, succeed",
            "One team, one dream",
            "Never give up, never surrender",
            "Chasing the dream, living the life",
            "Play with passion, play with heart",
            "The thrill of victory, the agony of defeat",
            "Football is life, everything else is just details",
            "The field is my cathedral",
            "Score, celebrate, repeat",
            "Leave it all on field",
            "Win as a team, lose as a team",
            "Faster, higher, stronger, together",
            "Fear no opponent, respect all",
            "Hustle, heart, champion attitude",
            "Chase the dream, catch success",
            "Never give up, always prevail",
            "Play, learn, grow, succeed",
            "Victory through persistence",
            "Adversity breeds champions",
            "Believe in yourself, shine",
            "One goal, one vision, one team",
            "Rise to the challenge",
            "Let your game speak",
            "11 warriors, 1 battle",
            "Passion, pride, and victory",
            "Game on, give it all",
            "Unleash your potential",
            "Champions never quit",
            "Victory or defeat, together",
            "Dream big, play bigger",
            "One chance, make it count",
            "Heart, dedication, success",
            "Perseverance leads to glory",
            "Goals, assists, wins",
            "Fierce determination, unwavering spirit",
            "Unbreakable team, unstoppable game",
            "Play to win, not just play",
            "Team work makes the dream work",
            "Victory starts with belief",
            "The stronger the team, the stronger the dream",
            "Passion fuels the fire",
            "Dare to be great",
            "Conquer your fears, seize the win",
            "Take control, leave your mark",
            "Chasing greatness, every day",
            "Unleash the beast within",
            "Chase success, leave nothing behind",
            "True strength lies in unity",
            "Victory through unity",
            "Chasing the impossible, making it reality",
            "Champions believe in themselves",
            "Make it happen, leave no regrets",
            "Risk it for the biscuit",
            "Victory is a mindset",
            "Leave nothing in the tank",
            "Chasing the dream, day by day",
            "Rise to greatness, chase the win",
            "Champions embrace the grind",
            "Victory at all costs",
            "Unstoppable spirit, relentless effort",
            "Conquer the pitch, conquer the world",
            "Champions never back down",
            "Victory is the goal, teamwork is the key",
            "Success is a choice",
            "Dream big, act bigger",
            "Champions play until the end",
            "Victory is just a step away",
            "Never settle, always strive",
            "Chasing glory, one game at a time",
            "Champions are made in training",
            "Take the field, make history",
            "Chasing greatness, never looking back",
            "Victory is in sight, keep pushing",
            "Rise to the challenge, every day",
            "Champions are made in the dark",
            "Victory is just a mindset",
            "Chasing excellence, in every aspect",
            "Never stop pushing, never stop winning",
            "Champions are built, not born",
            "Victory is not given, it's earned",
            "Chasing success, one game at a time",
            "Victory is just a mindset",
            "Champions are made through hard work",
            "Victory is not handed out, it's taken",
            "Chasing excellence, leaving a legacy",
            "Victory is just a step away",
            "Chasing glory, making history",
            "Victory is just a mindset",
            "Chasing success, always pushing forward",
            "Victory is earned, not given",
            "Chasing greatness, never settling",
            "Victory starts with a dream",
            "Chasing excellence, making a difference",
            "Victory is in the details",
            "Chasing success, one day at a time",
            "Victory is just a step away",
            "Arsenal: Shot more than target",
            "Chelsea: Blue is the color",
            "Man City: Blue moon rising",
            "Tottenham: Lillywhite army",
            "Liverpool: Red army marching",
            "Man United: Glory, glory Man U",
            "Everton: Toffees taste sweet",
            "West Ham: Hammers striking",
            "Leicester: Foxes on the prowl",
            "Wolves: Howling for glory",
            "Burnley: Clarets blazing trail",
            "Crystal Palace: Eagles soaring high",
            "Brighton: Seagulls flying high",
            "Newcastle: Magpies shining",
            "Aston Villa: Villans victorious",
            "Southampton: Saints marching on",
            "Bournemouth: Cherries picking up",
            "Watford: Hornets buzzing",
            "Norwich: Canaries chirping",
            "Sheffield United: Blades cutting deep",
            "Leeds United: Whites on a roll",
            "West Brom: Baggies flying high",
            "Fulham: Cottagers charging",
            "Arsenal: Gunners blazing",
            "Chelsea: Blues never lose",
            "Man City: Citizens conquering",
            "Tottenham: Spurs striking hard",
            "Liverpool: Reds unstoppable",
            "Man United: Devils dominating",
            "11 players, 1 heartbeat",
            "The beautiful game",
            "A pass, a shot, a goal",
            "Score with your feet, win with your heart",
            "Winning is a habit",
            "Play with passion, win with class",
            "A team is not just 11 players",
            "Success is a journey, not a destination",
            "Together we are stronger",
            "Teamwork makes the dream work",
            "Defend as one, attack as 11",
            "Play with heart, play with pride",
            "Experience the magic of football",
            "Heart of a champion, spirit of a winner",
            "The game is won in the mind",
            "One team, one dream",
            "Champions play until the end",
            "Never give up, always fight back",
            "Adversity builds character",
            "The journey is the reward",
            "Greatness takes time",
            "The road to success is always under construction",
            "Chase your dreams, catch your glory",
            "There's no finish line in football",
            "Create your own luck",
            "The first touch is the key",
            "A goal is not just a dream, it's a plan",
            "Always play with a purpose",
            "You miss 100% of the shots you don't take",
            "The biggest wins start with the smallest steps",
            "Success is where preparation and opportunity meet",
            "Success is not final, failure is not fatal",
            "The game never ends, only the time runs out",
            "The only limit is the one you set for yourself",
            "The power of teamwork makes the impossible possible",
            "Chase the ball, chase your dreams",
            "The field is where legends are born",
            "The greatest glory is in rising every time you fall",
            "You can't score if you don't shoot",
            "To play or not to play, there is no question",
            "Every game is an opportunity",
            "It's not the size of the player, but the size of the heart",
            "No excuses, just results",
            "The team that laughs together, wins together",
            "Go big or go home",
            "Leave it all on the field",
            "Play with fire",
            "Chase greatness",
            "Victory starts in the mind",
            "Let the games begin",
            "The future belongs to the brave",
            "Actions speak louder than words",
            "Play to win",
            "One love, one team",
            "Leave no stone unturned",
            "Dream big, play big",
            "The sky is the limit",
            "Make every touch count",
            "Always play with heart",
            "Be unstoppable",
            "Take it to the next level",
            "Unleash your potential",
            "Shoot for the stars",
            "The grind never stops",
            "Never settle for less",
            "Believe in the power of one",
            "Put in the work",
            "Play like a champion",
            "Rise to the challenge",
            "Expect greatness",
            "The game never stops",
            "Outwork your opponents",
            "Keep pushing forward",
            "The only way is up",
            "Don't be afraid to fail",
            "Work hard, play harder",
            "In football, anything can happen",
            "Do it for the love of the game",
            "The team that stays together, wins together",
            "In it to win it",
            "Never say die",
            "Chase your dreams, catch your glory",
            "Every day is a chance to win",
            "A game of inches",
            "No excuses, just results",
            "Champions play until the end",
            "Never give up, always fight back",
            "Success is a journey, not a destination",
            "Together we are stronger",
            "Teamwork makes the dream work",
            "Defend as one, attack as 11",
            "Play with passion, win with class",
            "Success is where preparation and opportunity meet",
            "Greatness takes time",
            "The road to success is always under construction",
            "Adversity builds character",
            "The journey is the reward",
            "The first touch is the key",
            "You miss 100% of the shots you don't take",
            "The biggest wins start with the smallest steps",
            "The power of teamwork makes the impossible possible",
            "The game is won in the mind",
            "Chase the ball, chase your dreams",
            "The field is where legends are born",
            "The greatest glory is in rising every time you fall",
            "Create your own luck",
            "Leave no stone unturned",
            "Dream big, play big",
            "The sky is the limit",
            "Make every touch count",
            "Always play with heart",
            "Be unstoppable",
            "Take it to the next level",
            "Unleash your potential",
            "Shoot for the stars",
            "The grind never stops",
            "Never settle for less",
            "Believe in the power of one",
            "Put in the work",
            "Play like a champion",
            "Rise to the challenge",
            "Expect greatness",
        ];
        foreach ($quotes as $quote) {
            Quote::create([
                'quote' => $quote,
            ]);
        }
    }
}